name: Build Windows Executable with Versioning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Step 4: Download and Add FFmpeg
      - name: Download FFmpeg
        run: |
          curl -L https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -o ffmpeg.zip
          tar -xf ffmpeg.zip -C ffmpeg --strip-components 1

      - name: Copy FFmpeg to Dist
        run: |
          cp -r ffmpeg/bin/* dist/

      - name: Add FFmpeg to PATH
        run: echo "%cd%\\ffmpeg\\bin" >> $GITHUB_PATH

      # Step 5: Build Executable
      - name: Build Executable
        run: |
          pyinstaller --onefile --add-data "templates;templates" --add-data "static;static" \
            --hidden-import "scipy.signal" --hidden-import "scipy._lib" --hidden-import "scipy.special" \
            --noconfirm image_to_sound.py

      # Step 6: Upload Executable
      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: Windows Executable
          path: dist/image_to_sound.exe

      # Step 7: Generate Version Number (Optional)
      - name: Generate Version
        id: version
        run: |
          echo "version=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV
        shell: bash

      - name: Add Version to Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "Windows Executable - ${{ env.version }}"
          path: dist/image_to_sound.exe
