# .github/workflows/build-windows.yml

name: Build Windows Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --add-data "templates;templates" --add-data "static;static" image_to_sound.py

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: Windows Executable
          path: dist/image_to_sound.exe
