name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow pydub moviepy flask numpy

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --icon=app_icon.ico image_to_sound.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Windows Executable
        path: dist/image_to_sound.exe

